### ISSUE TITLE
Symbol not found _clock_gettime 

### ISSUE THREAD

**Issue by coolmaksat** [gmiaslab/ClassificaIO#2]
Hi I'm getting the following error when I import ClassificaIO. Have you encountered this before? 
ImportError: dlopen(/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: lib/python3.6/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by raeufroushangar** [comment]
Hey coolmaksat, what version of Mac OS are you using?

**Comment by raeufroushangar** [comment]
Currently, when ClassificaIO is installed, the package is set to install and use Pillow >= 5.1.0. But Pillow 5.1.0 is supported on Mac OS X >= 10.12. So, If you are using Mac OS X < 10.12, I would recommend updating your Mac OS to >= 10.12 or try using Pillow version 5.0, which ClassificaIO also supports, rather than 5.1. To do the latter, type 'pip install Pillow==5.0' in your terminal and then run ClassificaIO in python3. Hope this helps.
